### ISSUE TITLE
Did you get any update for this radar?

### ISSUE THREAD

**Issue by katzenbaer** [rajivshah3/AutoFillReturn#1]
Hey @rajivshah3,

Just checking in. Have you gotten an update for this radar?

**Comment by rajivshah3** [comment]
Hi @katzenbaer , unfortunately I haven't gotten a reply yet

**Comment by katzenbaer** [comment]
Thanks for the info. Closing this issue.

For others reading this, I've found two possible solutions to this problem:

1. Disable "Auto-enable Return Key" or set `enablesReturnKeyAutomatically` to `false`, then validate whether the textField's contents are valid in `textFieldShouldReturn:`
2. Add another UITextField with the `textContentType = .username`. When Auto-Fill fills both a username `UITextField` and a password `UITextField`, the return key is enabled properly.
